apiVersion: gp.sjgs/v1alpha1
kind: GPDBCluster
metadata:
  name: dev-gpdbcluster
spec:
  masterAndStandby:
    replicas: 1
    image: busybox
    storageClassName: nfsclient
    storage: 2Gi
    hostBasedAuthentication: |
       host   all   gpadmin   0.0.0.0/0   md5
       host   all   gpuser    0.0.0.0/0   md5
       host   all   all    0.0.0.0/0   md5
  segments:
    replicas: 1
    image: busybox
    storageClassName: nfsclient
    storage: 1Gi
  mirrors:
    replicas: 1
    image: busybox
    storageClassName: nfsclient
    storage: 1Gi
  masterSelector: master-0